---
- hosts: all
  become: true

  tasks:

    - name: install software
      apt: name={{item}} state=latest update_cache=yes
      with_items:
        - lldpd
        - golang
        - git

    - name: bring up eth1
      command: ip link set up dev eth1
    
    - name: make dnet dir
      file:
        path: /home/rvn/.go/src/github.com/deter-project/switch-drivers
        state: directory

    - name: setup link dnet
      file:
        src: /opt/deter/switch-drivers/snmp
        dest: /home/rvn/.go/src/github.com/deter-project/switch-drivers/snmp
        state: link
    
    - name: configure go paths
      lineinfile:
        dest: /home/rvn/.bashrc
        line: "{{ item }}"
      with_items:
        - "export PATH=~/scripts:$PATH"
        - "export GOPATH=~/.go"
        - "export PATH=$GOPATH/bin:$PATH"

    - name: install go dependencies
      shell: go get {{ item }}
      environment:
        GOPATH: /home/rvn/.go
      with_items:
        - github.com/fatih/color
        - github.com/soniah/gosnmp

