---
- hosts: all
  become: true

  tasks:
    - name: set hostname
      hostname:
        name: {{.Host.Name}}

    - name: put hostname in /etc/hosts
      lineinfile:
        name: /etc/hosts
        line: '127.0.0.1    {{.Host.Name}}'

    - name: make sure nfs is installed
      apt: name=nfs-common state=latest update_cache=yes
      when: 
        - ansible_os_family == "Debian"
        - '"Cumulus" not in ansible_lsb.id'

{{range .Host.Mounts}}
    - name: mount {{.Point}}
      mount:
        name: {{.Point}}
        src: {{$.NFS}}:{{.Source}}
        fstype: nfs
        state: mounted
{{- end}}

