---
- hosts: all
  become: true

  tasks:
    - name: copy interfaces file
      copy:
        src: "{{ playbook_dir }}/leaf_interfaces"
        dest: /etc/network/interfaces
    
    - name: copy snmpd configuration
      copy:
        src: "{{ playbook_dir }}/snmpd.conf"
        dest: /etc/snmp/snmpd.conf
    
    - name: copy lldpd configuration
      copy:
        src: "{{ playbook_dir }}/lldpd.conf"
        dest: /etc/lldpd.d/lldpd.conf
    
    - name: copy lldpd defaults
      copy:
        src: "{{ playbook_dir }}/lldpd_default"
        dest: /etc/default/lldpd

    - name: bring up interfaces
      command: ifup -a

    - name: restart lldpd
      service:
        name: lldpd
        state: restarted
    
    - name: restart snmpd
      service:
        name: snmpd
        state: restarted
