---
- hosts: all
  become: true

  tasks:

    - name: install software
      apt: name={{item}} state=latest update_cache=yes
      with_items:
        - lldpd

    - name: bring up eth1
      command: ip link set up dev eth1

    - name: bring up eth2
      command: ip link set up dev eth2

